import type { NewProduct } from "./schema.js";
import { createProductEmbedding } from "./embedding.js";

type SeedProduct = Omit<NewProduct, "embedding">;

const seedProducts: SeedProduct[] = [
  {
    slug: "trail-runner-waterproof",
    name: "Trail Runner Waterproof",
    category: "shoes",
    description: "Lightweight waterproof running shoes for wet trail and mountain routes.",
    tags: ["outdoor", "running", "waterproof", "lightweight"],
    priceCents: 14800,
    rating: 4.7,
    popularityScore: 92,
    stock: 24,
  },
  {
    slug: "city-walk-sneaker",
    name: "City Walk Sneaker",
    category: "shoes",
    description: "Compact daily sneakers for commuting, walking, and casual city use.",
    tags: ["shoe", "sneaker", "compact", "daily"],
    priceCents: 8900,
    rating: 4.3,
    popularityScore: 73,
    stock: 48,
  },
  {
    slug: "alpine-camp-jacket",
    name: "Alpine Camp Jacket",
    category: "apparel",
    description: "Durable waterproof outdoor jacket for camping, hiking, and sudden rain.",
    tags: ["outdoor", "camping", "waterproof", "durable"],
    priceCents: 21800,
    rating: 4.6,
    popularityScore: 81,
    stock: 17,
  },
  {
    slug: "home-espresso-mini",
    name: "Home Espresso Mini",
    category: "kitchen",
    description: "Compact espresso maker for home coffee and small kitchen counters.",
    tags: ["coffee", "kitchen", "home", "compact"],
    priceCents: 16800,
    rating: 4.4,
    popularityScore: 68,
    stock: 12,
  },
  {
    slug: "bakers-stand-mixer",
    name: "Baker's Stand Mixer",
    category: "kitchen",
    description: "Powerful kitchen stand mixer for baking bread, cake, and pastry dough.",
    tags: ["kitchen", "baking", "mixer", "home"],
    priceCents: 32800,
    rating: 4.8,
    popularityScore: 86,
    stock: 9,
  },
  {
    slug: "wireless-workout-earbuds",
    name: "Wireless Workout Earbuds",
    category: "electronics",
    description: "Sweat-resistant wireless earbuds with long battery life for running and gym workouts.",
    tags: ["electronics", "wireless", "fitness", "running"],
    priceCents: 11800,
    rating: 4.2,
    popularityScore: 89,
    stock: 35,
  },
  {
    slug: "portable-camp-lantern",
    name: "Portable Camp Lantern",
    category: "outdoor",
    description: "Small rechargeable lantern for camping, hiking, and outdoor night use.",
    tags: ["outdoor", "camping", "portable", "battery"],
    priceCents: 6400,
    rating: 4.1,
    popularityScore: 58,
    stock: 41,
  },
  {
    slug: "premium-yoga-mat",
    name: "Premium Yoga Mat",
    category: "fitness",
    description: "Durable non-slip mat for yoga, home workouts, and gym training.",
    tags: ["fitness", "yoga", "home", "premium"],
    priceCents: 7600,
    rating: 4.5,
    popularityScore: 77,
    stock: 29,
  },
  {
    slug: "compact-home-desk",
    name: "Compact Home Desk",
    category: "home",
    description: "Small desk for home office rooms, laptops, and compact interiors.",
    tags: ["home", "desk", "compact", "interior"],
    priceCents: 13900,
    rating: 4.0,
    popularityScore: 63,
    stock: 14,
  },
  {
    slug: "pro-cookware-pan",
    name: "Pro Cookware Pan",
    category: "kitchen",
    description: "Premium durable pan for home cooking, searing, and daily kitchen use.",
    tags: ["kitchen", "cooking", "premium", "durable"],
    priceCents: 9600,
    rating: 4.6,
    popularityScore: 71,
    stock: 21,
  },
];

export function buildSeedProducts(): NewProduct[] {
  return seedProducts.map((product) => ({
    ...product,
    embedding: createProductEmbedding(product),
  }));
}
